# Generated by Django 5.1.7 on 2025-03-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qpmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpaper',
            name='subject_code',
            field=models.CharField(blank=True, help_text="Optional. If left blank, the subject's code will be used.", max_length=20),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
