name: Deploy to Azure

on:
  push:
    branches:
      - master  # Change this if your default branch is different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Collect static files
      run: |
        python manage.py collectstatic --noinput
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DEBUG: 'False'
        ALLOWED_HOSTS: '.azurewebsites.net'
    
    - name: Create deployment package
      run: |
        zip -r deploy.zip . -x "*.git*" -x "*.github*" -x "*.venv*" -x "*__pycache__*" -x "*.pytest_cache*"
    
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./deploy.zip 